### PR TITLE
Update Legenden.kt

### PR DESCRIPTION
**Pull request by 3Digits**
😐

### CODE REVIEW

**Comment by jakobkmar** [comment]
was soll das

**Comment by 3Digits** [comment]
> was soll das

gönn

**Review by jakobkmar — CHANGES_REQUESTED** [review]
The information given about 3Digits is not valuable enough.

**Comment by jakobkmar** [comment]
Maybe we should create a new command `/userinfo`?

**Comment by 3Digits** [comment]
> The information given about 3Digits is not valuable enough.

was soll das jetzt heißen bin ich etwa keine Legende? 😭

**Comment by jakobkmar** [comment]
grafik

**Comment by 3Digits** [comment]
> Maybe we should create a new command `/userinfo`?

no

**Comment by 3Digits** [comment]
> Maybe we should create a new command `/userinfo`?

great Idea how could we implement this in the BlauBot? 👍 🤔 😸

**Comment by jakobkmar** [comment]
I will do that

**Pull request closed without merging**
