### PR TITLE
Name Hsitory Card

### PR DESCRIPTION
**Pull request by 0skxr**
This is a name history card codet bei Taito/NoMacroo but is hosted by me. (edit haha no I coded it lol)
Source : https://github.com/NooMacroo/NameHistoryCard

The app.py is merged with some code of me so i can have 2 things on one server :D

### CODE REVIEW

**Comment by 0skxr** [comment]
Please Review

**Comment by flerbuster** [comment]
ich werd nicht mehr

**Comment by jakobkmar** [comment]
would merge this once it uses the mojang API directly

**Comment by 0skxr** [comment]
Nah, its not even online anymore. But if you think it is a useful feature for the BlauBot I could rewrite it so that it is using the Mojang API and put it online again.

**Comment by jakobkmar** [comment]
no I was speaking about the bot accessing the mojang API directly

**Pull request closed without merging**
